name: SonarCloud scan

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - 8.0.x
        java-distribution:
          - temurin

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Build with Maven
        run: >
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
