name: Build

on:
  pull_request:
    type: [opened, edited, synchronize, reopened]
    branches:
      - develop
      - staging
      - main
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [1.8]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '1.8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml